---
title: "nonames2"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/maxand22/Google Drive/Humboldt/4. Semester/Machine Intelligence II/Machine_Intelligence_II/")
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```



```{r packages}


```



```{r helper functions}

mean_field <- function(w, s, i){
  mean_field_value <- 0
  for(j in N){
    #diagonal is zero so k equals i is never calculated
    mean_field_value <- (w[i,j]*s[j]) + mean_field_value
  }
  
 return((-1)*mean_field_value)
}

state <- function(beta,mean_field_value){
  s <- tanh((-1)*beta*mean_field_value)
  return(s)
}

```


weight initalization
```{r weight initalization}
N <- 6

#assumption
set.seed(221)
W <- matrix(rnorm(N*N,0,1),N,N)
diag(W) <- 0 
W
```


beta, tau, tmax, state, e
```{r initalization}
beta0 <- 0.1
tau <- 1.3
M <- 500
t_max <- 100
e <- 0.2

# set s randomly
set.seed(123)
s0 <- sample(c(-1,1),6, replace = TRUE)

Energy <- matrix(nrow = 1, ncol = t_max)

```


mean-field algorithm
```{r initalization}

for(t in 1:t_max){
  
  if(t == 1){
    s <- s0
    beta <- beta0
  }
  
  enew <- 1
  eold <- 0
  while(abs(enew - eold) > e){
    
    if(eold == 0){}else{eold <- mean_field_value}

     for(i in 1:N){
        mean_field_value <- mean_field(W, s, i)
        s[i] <- state(beta, mean_field_value)
      } # end mean field annealing algorithm
    enew <- mean_field_value
  }
  beta <- beta*tau
  
  #Plot the temperature Tt = 1 and the energy Et over the iterations t = 0, . . . , tmax.
  Energy[i] <- mean_field_value
  
} #end annealing loop
```



Plot the temperature Tt = 1 and the energy Et over the iterations t = 0, . . . , tmax.
```{r plot}
plot(1:t_max, Energy, type = 'l')
```